---
abstract: 'process runner with RAII pattern'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Proc-Guard
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Lite: 0
  Exporter: 5.63
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
